#!/bin/bash -e

. $(dirname ${0})/shared.sh

install -dm755 ${LFS}/{etc,dev,proc}
install -dm755 ${LFS}/var/lib/pacman
install -dm755 ${LFS}/var/cache/pacman/pkg

/tools/bin/pacman -D -kk

mknod -m 600 ${LFS}/dev/console c 5 1
mknod -m 666 ${LFS}/dev/null c 1 3

mount --bind /dev ${LFS}/dev
mount --bind /dev/pts ${LFS}/dev/pts

mount -t proc none ${LFS}/proc

cat > ${LFS}/etc/group << EOF
root:x:0:root
pkgbuild:x:${PKGBUILD_ID}:pkgbuild
EOF

cat > ${LFS}/etc/passwd << EOF
root:x:0:0:root:/:/tools/bin/bash
pkgbuild:x:${PKGBUILD_ID}:${PKGBUILD_ID}:pkgbuild:${BUILDDIR}:/tools/bin/bash
EOF

lfs_chroot_build_temp filesystem

umount ${LFS}/dev/pts ${LFS}/dev ${LFS}/proc

rm -rf ${LFS}/{dev,etc,proc}

lfs_pacman_install_temp filesystem

ln -sf /tools/bin/{bash,cat,echo,pwd,stty} ${LFS}/bin
ln -sf /tools/bin/perl ${LFS}/usr/bin

ln -sf /tools/lib/libgcc_s.so ${LFS}/usr/lib
ln -sf /tools/lib/libgcc_s.so.1 ${LFS}/lib

ln -sf /tools/lib/libstdc++.so{,.6} ${LFS}/usr/lib
ln -sf /tools/lib32/libgcc_s.so{,.1} ${LFS}/usr/lib32
ln -sf /tools/lib32/libstdc++.so{,.6} ${LFS}/usr/lib32

ln -sf /tools/lib/libc++.so{,.1} ${LFS}/usr/lib
ln -sf /tools/lib/libc++abi.so{,.1} ${LFS}/usr/lib
ln -sf /tools/lib32/libc++.so{,.1} ${LFS}/usr/lib32
ln -sf /tools/lib32/libc++abi.so{,.1} ${LFS}/usr/lib32

ln -sf /tools/lib/libomp.so ${LFS}/usr/lib
ln -sf /tools/lib32/libomp.so ${LFS}/usr/lib32

ln -sf bash ${LFS}/bin/sh

PKGS=(linux-api-headers
glibc
tzdata
zlib
file
m4
bison
flex
attr
acl
gmp
mpfr
mpc
ncurses
readline
bzip2
xz
pcre
libsepol
libselinux
sed
pkg-config
binutils
gcc
libutil-linux
e2fsprogs
procps-ng
bc
psmisc
cracklib
libcap-ng
openssl
tcl
ustr
audit
db
pam
libcap
libsemanage
bash
coreutils
grep
shadow
expat
gdbm
libffi
libtool
sqlite
hostname
run-parts
which
perl
python2
python3
autoconf
automake
diffutils
findutils
gawk
gperf
groff
gzip
make
patch
tar
texinfo
check
libmnl
libnftnl
iptables
less
libpipeline
iproute2
kbd
kmod
man-db
nano
unzip
zip
perl-xml-parser
perl-archive-zip
perl-error
perl-parse-yapp
perl-sgmls
perl-uri
icu
boost
libgpg-error
libgcrypt
libidn
libunistring
libxml2
libxslt
lua
highlight
ca-certificates
wget
docbook-xml
docbook-xsl
intltool
itstool
xmlto
sgml-common
docbook
docbook-dsssl
opensp
openjade
docbook-utils
asciidoc
gtk-doc
glib
libcroco
gettext
python-six
python-packaging
python-setuptools
python-alabaster
python-beaker
python-cssselect
python-decorator
python-imagesize
python-ipy
python-isodate
python-markupsafe
python-pyparsing
python-pygments
python-pytz
python-pyxdg
python-snowballstemmer
python-babel
python-docutils
python-jinja2
python-lxml
python-mako
python-networkx
python-rdflib
python-requests
python-sphinx
python-sphinx_rtd_theme
elfutils
gobject-introspection
libaio
libatomic_ops
libedit
libpng
libsasl
libssh2
libtasn1
libuv
lz4
lzo
nettle
nspr
nss
openldap
p11-kit
popt
rtmpdump
vala
chrpath
gc
gnutls
krb5
libarchive
curl
cyrus-sasl
libmicrohttpd
pixman
swig
cmake
llvm
freetype
fontconfig
util-macros
bigreqsproto
compositeproto
damageproto
dmxproto
dri2proto
dri3proto
fixesproto
fontsproto
glproto
inputproto
kbproto
presentproto
randrproto
recordproto
renderproto
resourceproto
scrnsaverproto
videoproto
xcmiscproto
xextproto
xf86bigfontproto
xf86dgaproto
xf86driproto
xf86vidmodeproto
xineramaproto
xproto
xcb-proto
xtrans
libxau
libxdmcp
libxcb
libx11
libxext
libfs
libice
libsm
libxscrnsaver
libxt
libxmu
libxpm
libxaw
libxfixes
libxcomposite
libxrender
libxcursor
libxdamage
libfontenc
libxfont2
libxft
libxi
libxinerama
libxrandr
libxpresent
libxres
libxtst
libxv
libxvmc
libxxf86dga
libxxf86vm
libdmx
libpciaccess
libxkbfile
libxshmfence
xcb-util
xcb-util-errors
xcb-util-image
xcb-util-keysyms
xcb-util-renderutil
xcb-util-wm
xcb-util-cursor
pciutils
qrencode
wayland
wayland-protocols
xkeyboard-config
gnu-efi-libs
libseccomp
libxkbcommon
libsystemd
lvm2
cryptsetup
util-linux
systemd
cairo
graphite2
harfbuzz
freetype
libdrm
libusb
libusb-compat
fakeroot
iana-etc
usbutils
libassuan
libksba
npth
gnupg
gpgme
pacman
dbus
dbus-glib
dbus-python
libselinux-python
libsemanage-python
checkpolicy
sepolgen
setools
policycoreutils
htop
intel-ucode
lsb-release
man-pages
nasm
scons
yasm
apr
apr-util
fuse
guile
libevent
libical
libgnome-keyring
libgudev
libsecret
serf
tk
yaml
bluez
git
ntfs-3g
ruby
subversion
linux-firmware
libomxil-bellagio
libva
libvdpau
opencl-headers
ocl-icd
vulkan-loader
mesa
libva
glu
freeglut
libjpeg-turbo
tiff
giflib
jasper
lcms2
libwebp
atk
gdk-pixbuf
pango
librsvg
links
xdg-utils
libdaemon
libgusb
mozjs
polkit
colord
libavahi
cups
gtk2
hicolor-icon-theme
libepoxy
libevdev
libunwind
mtdev
libwacom
libinput
at-spi2-core
at-spi2-atk
json-glib
gtk3
adwaita-icon-theme
avahi
cantarell-fonts
dconf
desktop-file-utils
gnome-themes-standard
gsettings-desktop-schemas
shared-mime-info
xbitmaps
xorg-font-util
xorg-iceauth
xorg-luit
xorg-mkfontdir
xorg-mkfontscale
xorg-sessreg
xorg-setxkbmap
xorg-smproxy
xorg-x11perf
xorg-xauth
xorg-xbacklight
xorg-xcmsdb
xorg-xcursorgen
xorg-xdpyinfo
xorg-xdriinfo
xorg-xev
xorg-xgamma
xorg-xhost
xorg-xinput
xorg-xkbcomp
xorg-xkbevd
xorg-xkbutils
xorg-xkill
xorg-xlsatoms
xorg-xlsclients
xorg-xmessage
xorg-xmodmap
xorg-xpr
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xrefresh
xorg-xset
xorg-xsetroot
xorg-xvinfo
xorg-xwd
xorg-xwininfo
xorg-xwud
xcursor-themes
xorg-server
xf86-input-libinput
xf86-input-wacom
xf86-video-amdgpu
xf86-video-intel
weston
iso-codes
libnotify
py2cairo
pycairo
pygobject
ibus
talloc
tdb
tevent
ldb
jansson
libmbim
libndp
libnl
libpcap
libsoup
slang
libqmi
libteam
newt
dhcp
modemmanager
ppp
wpa_supplicant
networkmanager
json-c
libasyncns
orc
alsa-lib
libogg
libvorbis
libtheora
cdparanoia
flac
libvisual
speexdsp
speex
libsndfile
opus
sbc
soxr
webrtc-audio-processing
pulseaudio
alsa-plugins
alsa-utils)

for pkg in "${PKGS[@]}"
do
  pushd "$(dirname $(realpath $0))/pkgbuild/${pkg}"
    rm -f $(dirname $(realpath $0))/${pkg}.log.gz
    ./build 2>&1 | tee $(dirname $(realpath $0))/${pkg}.log
    gzip $(dirname $(realpath $0))/${pkg}.log
  popd
done
