#!/bin/bash -e

# Cleanup
mountpoint /media/ntfs 2>&1> /dev/null && umount /media/ntfs
rm -rf /media/ntfs /tools

userdel pkgbuild

systemctl enable accounts-daemon auditd avahi-daemon bluetooth ModemManager named NetworkManager NetworkManager-dispatcher rtkit-daemon systemd-timesyncd upower wpa_supplicant
systemctl enable sshd.socket

install -dm755 /media/ntfs /media/other /media/win
install -dm755 /etc/wpa_supplicant

cat > /etc/fstab << "EOF"
#
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>

/dev/sda9 /     ext4 noatime,errors=remount-ro 0 1
/dev/sda8 /home ext4 noatime                   0 2
/dev/sda7 none  swap defaults                  0 0

/dev/sda2 /boot vfat defaults                  0 0

none /var/tmp tmpfs defaults 0 0

UUID=5228A9FE28A9E169 /media/win   ntfs defaults 0 0
UUID=C228EA6328EA5647 /media/ntfs  ntfs defaults 0 0
UUID=3CB8F34AB8F30166 /media/other ntfs defaults 0 0
EOF

useradd -u 1000 -c "Armin K" -s /bin/bash -MU armin

gpasswd -a armin kvm
gpasswd -a armin systemd-journal
gpasswd -a armin wireshark

cat > /etc/hosts << "EOF"
# Begin /etc/hosts

127.0.0.1	localhost	localhost.localdomain
::1		localhost	localhost.localdomain
127.0.1.1	krejzi

# End /etc/hosts
EOF

echo "krejzi" > /etc/hostname
echo "nameserver 127.0.0.1" > /etc/resolv.conf

ln -sf /usr/share/zoneinfo/Europe/Sarajevo /etc/localtime

cat > /etc/locale.conf << "EOF"
LANG=en_US.UTF-8
EOF

cat > /etc/vconsole.conf << "EOF"
KEYMAP=croat
FONT=Lat2-Terminus16
FONT_MAP=8859-2
EOF

cat > /etc/X11/xorg.conf.d/00-keyboard.conf << "EOF"
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "hr"
        Option "XkbModel" "pc105"
EndSection
EOF

#cat > /etc/X11/xorg.conf.d/90-tigervnc.conf << "EOF"
#Section "Module"
#	Load		"vnc"
#EndSection

#Section "Screen"
#	Identifier	"Screen0"
#	DefaultDepth	24
#	Option		"SecurityTypes"		"VncAuth"
#	Option		"UserPasswdVerifier"	"VncAuth"
#	Option		"PasswordFile"		"/home/armin/.vnc/passwd"
#EndSection
#EOF

echo -e "armin ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/99-local

chmod 440 /etc/sudoers.d/99-local

sed -i "s:#HandleLidSwitch=suspend:HandleLidSwitch=ignore:g" /etc/systemd/logind.conf
sed -i "s:#DefaultTimeoutStopSec=90s:DefaultTimeoutStopSec=30s:g" /etc/systemd/system.conf

systemctl enable gdm

echo "Entering password for user root:"
passwd
echo "Entering password for user armin:"
passwd armin

systemd-machine-id-setup

rm -rf  /etc/group- /etc/gshadow- /etc/passwd- /etc/shadow-

cat << "EOF"
Now run the following from outside the chroot

export LFS=/mnt/lfs

install -m600 /media/ntfs/Other/Linux/conf/nm/* ${LFS}/etc/NetworkManager/system-connections
install -m644 /media/ntfs/Other/Linux/conf/network/* ${LFS}/etc/systemd/network
install -m600 /media/ntfs/Other/Linux/conf/wpa/* ${LFS}/etc/wpa_supplicant

for D in AccountsService alsa bluetooth   \
         NetworkManager upower            \
         systemd/backlight systemd/rfkill
do
  rm -rf $LFS/var/lib/${D}
  cp -a /var/lib/${D} ${LFS}/var/lib/${D}
done

umount ${LFS}/sources
rmdir ${LFS}/sources
EOF
