#!/bin/bash -e

thisdir=$(realpath $(dirname ${0}))
thispkg=$(basename ${thisdir})
realfile=$(realpath ${0})
realfilepath=$(dirname ${realfile})

. ${realfilepath}/shared.sh

lfs_mount_virt

lfs_chroot_build_temp ${thispkg} || exit 1

case ${thispkg} in
  "bash" )
    rm -rf ${LFS}/bin/{bash,sh}
  ;;
  "coreutils" )
    rm -rf ${LFS}/bin/{cat,dd,echo,ln,pwd,rm,stty}
    rm -rf ${LFS}/usr/bin/install
  ;;
  "gcc" )
    rm -rf ${LFS}/usr/lib/libgcc_s.so ${LFS}/lib/libgcc_s.so.1 ${LFS}/usr/lib/libstdc++.so{,.6}
    rm -rf ${LFS}/usr/lib32/libgcc_s.so{,.1} ${LFS}/usr/lib32/libstdc++.so{,.6}
  ;;
  "llvm" )
    rm -rf ${LFS}/usr/lib/libc++.so{,.1} ${LFS}/usr/lib/libc++abi.so{,.1} ${LFS}/usr/lib/libomp.so
    rm -rf ${LFS}/usr/lib32/libc++.so{,.1} ${LFS}/usr/lib32/libc++abi.so{,.1} ${LFS}/usr/lib32/libomp.so
  ;;
  "perl" )
    rm -rf ${LFS}/usr/bin/perl
  ;;
esac

lfs_pacman_install_temp ${thispkg} || exit 1

case ${thispkg} in
  "glibc" )
    echo "Adjusting the toolchain"

    mv -v /tools/bin/{ld,ld-old}
    mv -v /tools/bin/{ld-new,ld}

    /tools/bin/gcc -dumpspecs | sed -e 's@/tools@@g'                   \
                   -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
                   -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' >      \
                   `dirname $(/tools/bin/gcc --print-libgcc-file-name)`/specs

    for L in bs_BA en_US hr_HR
    do
      sed -i "s:^#${L}:${L}:g" ${LFS}/etc/locale.gen
    done

    lfs_chroot_exec_cmd locale-gen
  ;;
  "systemd" )
    lfs_chroot_exec_cmd "systemd-sysusers /usr/lib/sysusers.d/slapd.conf"
  ;;
esac

lfs_umount_virt
