#!/bin/bash -e

KF5VER=5.9.2

PKGS=(qtbase
qtimageformats
qtnetworkauth
qtscript
qtserialport
qtsvg
qtx11extras
qtxmlpatterns
qtdeclarative
qt3d
qtcanvas3d
qtcharts
qtconnectivity
qtdatavis3d
qtgamepad
qtgraphicaleffects
qtlocation
qtmultimedia
qtquickcontrols
qtquickcontrols2
qtscxml
qtsensors
qtserialbus
qtspeech
qttools
qtvirtualkeyboard
qtwayland
qtwebchannel
qtwebsockets
qtwebengine
qtwebview)

for pkg in ${PKGS[@]}
do
  pushd ${pkg}
    rm -f ${pkg}*.tar.xz
    sed -i "s#pkgver=.*#pkgver=${KF5VER}#g" PKGBUILD
    sed -i "/sha512sums=('/,/')/d" PKGBUILD
    makepkg --geninteg >> PKGBUILD
    rmdir src
  popd
done
