#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf gettext-${GETTEXT_VER} ${LOGDIR}/gettext-${GETTEXT_VER}.log

tar xf ${SROOT}/gettext-${GETTEXT_VER}.tar.xz

{

  time {
  pushd gettext-${GETTEXT_VER}
    ./configure --prefix=/tools --disable-shared
    sed -i "/libgnuintl.so/d" gettext-tools/intl/Makefile
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/gettext-${GETTEXT_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf gettext-${GETTEXT_VER}
