#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf attr-${ATTR_VER} ${LOGDIR}/attr-${ATTR_VER}.log

tar xf ${SROOT}/attr-${ATTR_VER}.tar.gz

{

  time {
  pushd attr-${ATTR_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/attr-${ATTR_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf attr-${ATTR_VER}
