#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf expat-${EXPAT_VER} ${LOGDIR}/expat-${EXPAT_VER}.log

tar xf ${SROOT}/expat-${EXPAT_VER}.tar.bz2

{

  time {
  pushd expat-${EXPAT_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/expat-${EXPAT_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf expat-${EXPAT_VER}
