#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf curl-${CURL_VER} ${LOGDIR}/curl-${CURL_VER}.log

tar xf ${SROOT}/curl-${CURL_VER}.tar.xz

{

  time {
  pushd curl-${CURL_VER}
    ./configure --prefix=/tools            \
                --with-ssl                 \
                --enable-threaded-resolver \
                --with-ca-bundle=/tools/etc/ssl/certs/ca-certificates.crt
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/curl-${CURL_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf curl-${CURL_VER}
