#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf git-${GIT_VER} ${LOGDIR}/git-${GIT_VER}.log

tar xf ${SROOT}/git-${GIT_VER}.tar.xz

{

  time {
  pushd git-${GIT_VER}
    ./configure --prefix=/tools                  \
                --with-editor=/tools/bin/nano    \
                --with-perl=/tools/bin/perl      \
                --with-python=/tools/bin/python3 \
                --without-tcltk
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/git-${GIT_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf git-${GIT_VER}
