#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf Python-${PYTHON3_VER} ${LOGDIR}/python-${PYTHON3_VER}.log

tar xf ${SROOT}/Python-${PYTHON3_VER}.tar.xz

{

  time {
  pushd Python-${PYTHON3_VER}
    ./configure --prefix=/tools     \
                --enable-shared     \
                --with-system-expat \
                --with-system-ffi
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/python-${PYTHON3_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf Python-${PYTHON3_VER}
