#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf cmake-${CMAKE_VER} ${LOGDIR}/cmake-${CMAKE_VER}.log

tar xf ${SROOT}/cmake-${CMAKE_VER}.tar.gz

{

  time {
  pushd cmake-${CMAKE_VER}
    ./bootstrap --prefix=/tools           \
                --system-bzip2            \
                --system-curl             \
                --system-expat            \
                --system-libarchive       \
                --system-liblzma          \
                --system-zlib             \
                --mandir=/share/man       \
                --docdir=/share/doc/cmake \
                --parallel=$(nproc)
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/cmake-${CMAKE_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf cmake-${CMAKE_VER}
