#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf pacman-${PACMAN_VER} ${LOGDIR}/pacman-${PACMAN_VER}.log

tar xf ${SROOT}/pacman-${PACMAN_VER}.tar.gz

{

  time {
  pushd pacman-${PACMAN_VER}
    sed -i "s#CPPFLAGS CFLAGS CXXFLAGS LDFLAGS#CC CXX &#" scripts/makepkg.sh.in
    sed -i "/C*LAGS+=.*DEBUG/s#FLAGS+=#FLAGS=#g" scripts/makepkg.sh.in
    patch -Np1 -i ${PROOT}/pacman.patch
    ./configure --prefix=/tools   \
                --without-gpgme   \
                --without-libcurl
    make
    make install

    sed -i "s#/usr/bin#/tools/bin#g" /tools/bin/makepkg

    cat > /tools/etc/makepkg.conf << "EOF"
DLAGENTS=('ftp::/tools/bin/curl -fC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
          'http::/tools/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'https::/tools/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u'
          'rsync::/usr/bin/rsync --no-motd -z %u %o'
          'scp::/usr/bin/scp -C %u %o')

VCSCLIENTS=('bzr::bzr'
            'git::git'
            'hg::mercurial'
            'svn::subversion')

CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

CC=clang
CXX=clang++

CPPFLAGS=""
CFLAGS="-march=skylake -fomit-frame-pointer -O2 -pipe"
CXXFLAGS="-march=skylake -fomit-frame-pointer -O2 -pipe"
LDFLAGS=""

MAKEFLAGS="-j4"

DEBUG_CFLAGS="-march=skylake -g -O2 -pipe"
DEBUG_CXXFLAGS="-march=skylake -g -O2 -pipe"

BUILDENV=(!distcc color !ccache check !sign)
OPTIONS=(strip !docs !libtool !staticlibs !emptydirs zipman purge !optipng !upx !debug)

INTEGRITY_CHECK=(md5)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"

MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
DOC_DIRS=(usr/{,local/}{,share/}doc opt/*/doc)
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)

COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -z -)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZO=(lzop -q)
COMPRESSZ=(compress -c -f)

PKGEXT='.pkg.tar'
SRCEXT='.src.tar.gz'
EOF

    cat >>  /tools/etc/pacman.conf << EOF
DBPath      = ${LFS}/var/lib/pacman/
CacheDir    = ${LFS}/var/cache/pacman/pkg/
LogFile     = ${LFS}/var/log/pacman.log
EOF
  popd
  }

} 2>&1 | tee ${LOGDIR}/pacman-${PACMAN_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf pacman-${PACMAN_VER}
