#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf autoconf-${AUTOCONF_VER} ${LOGDIR}/autoconf-${AUTOCONF_VER}.log

tar xf ${SROOT}/autoconf-${AUTOCONF_VER}.tar.xz

{

  time {
  pushd autoconf-${AUTOCONF_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/autoconf-${AUTOCONF_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf autoconf-${AUTOCONF_VER}
