#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf automake-${AUTOMAKE_VER} ${LOGDIR}/automake-${AUTOMAKE_VER}.log

tar xf ${SROOT}/automake-${AUTOMAKE_VER}.tar.xz

{

  time {
  pushd automake-${AUTOMAKE_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/automake-${AUTOMAKE_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf automake-${AUTOMAKE_VER}
