#!/bin/bash -e

. $(dirname $0)/000_shared

rm -rf libtool-${LIBTOOL_VER} ${LOGDIR}/libtool-${LIBTOOL_VER}.log

tar xf ${SROOT}/libtool-${LIBTOOL_VER}.tar.xz

{

  time {
  pushd libtool-${LIBTOOL_VER}
    ./configure --prefix=/tools
    make
    make install
  popd
  }

} 2>&1 | tee ${LOGDIR}/libtool-${LIBTOOL_VER}.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -rf libtool-${LIBTOOL_VER}
